Allow change of time and date formats on lock screen.
mate-desktop/mate-screensaver pull request #252
Opened 2021-06-06 14:57 UTC by eugenesan

This change allows modification of default time and date format defined by current locale.
Closes https://github.com/mate-desktop/mate-screensaver/issues/100

Default ('local') settings maintains old behavior.
User is able to use any format defined by https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format.

Examples:
%R for time means 24H format.
%F for date means YYYY-MM-DD (ISO 8601 format).

2021-06-22 16:48 UTC, raveit65 approved these changes
LGTM,
nice change and it does what it promise.

2021-06-23 19:03 UTC, mbkma requested changes
- tfmt, dfmt need to be of type gchar (see https://developer.gnome.org/gio/stable/GSettings.html#g-settings-get-string) 
- You need to free tfmt and dfmt with g_free
- You need to free gchar* when overwriting them
- You should use g_strcmp0 (https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strcmp0) instead of strcmp (it is null safe)

2021-06-25 02:50 UTC, eugenesan commented
>     * tfmt, dfmt need to be of type gchar (see https://developer.gnome.org/gio/stable)/GSettings.html#g-settings-get-string)
> 
>     * You need to free tfmt and dfmt with g_free
> 
>     * You need to free gchar* when overwriting them
> 
>     * You should use g_strcmp0 (https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strcmp0) instead of strcmp (it is null safe)

Oppsie, silly me.
I was in such a rush that I forgot we are in "gnome" environment and stuff needs to be released ;-)
I am sure going to apply all your recommendations.

Also, I wonder if I can skip checking return value of g_date_time_format()?
Looks like it always outputs proper string.
If the parsing fails, it just outputs input string.
Worst case scenario the user will see that and correct.

2021-07-10 11:50 UTC, raveit65 commented
@mbkma 
Are your concerns solved?

2021-07-10 12:14 UTC, mbkma reviewed
besides a few indent issues it is good :)

2021-07-10 12:14 UTC, mbkma commented on src/gs-lock-plug.c
> +        else
indent (`else` should be aligned with `if`)

2021-07-10 12:14 UTC, mbkma commented on src/gs-lock-plug.c
> +        else
indent (`else` should be aligned with `if`)

2021-07-10 12:14 UTC, mbkma commented on src/gs-lock-plug.c
> +	gchar  *tfmt;
indent (`*tfmt` and `*dfmt` should be aligned with `*date`)

2021-07-24 11:00 UTC, raveit65 commented
@eugenesan 
Any chance to fix this indent issues?

2021-07-24 13:12 UTC, eugenesan commented
@raveit65 
Sorry for the delay (I was away).
I've pushed requested changes.

2021-07-24 14:00 UTC, raveit65 approved these changes
Intends issues are fixed and screensaver runs fine.

2021-07-24 14:14 UTC, mbkma approved these changes
thanks for contributing, it works as expected

2021-07-24 14:17 UTC, merged