Add the lock screen time function after updating and activating the screen save
mate-desktop/mate-screensaver pull request #293
Opened 2024-05-09 11:12 UTC by zhuyaliang

2024-05-14 17:40 UTC, cwendling requested changes

2024-05-14 17:40 UTC, cwendling commented on data/mate-screensaver-preferences.ui
> +-                                   <property name="spacing">12</property>
Somehow this doesn't break everything, but there shouldn't be leading dashes/minuses.
```suggestion
                                    <property name="visible">True</property>
                                    <property name="can_focus">False</property>
                                    <property name="spacing">12</property>
```

2024-05-14 17:40 UTC, cwendling commented on data/mate-screensaver-preferences.ui
Overall changes I suggest:
* remove spurious leading dashes
* use a grid with variable column widths instead of 4 columns with manual ¼/¾
* align labels to the left

```diff
diff --git a/data/mate-screensaver-preferences.ui b/data/mate-screensaver-preferences.ui
index c49b04c..0237f75 100644
--- a/data/mate-screensaver-preferences.ui
+++ b/data/mate-screensaver-preferences.ui
@@ -394,20 +394,21 @@
                                 <property name="spacing">6</property>
                                 <child>
                                   <object class="GtkBox" id="activate_delay_hbox">
--                                   <property name="visible">True</property>
--                                   <property name="can_focus">False</property>
--                                   <property name="spacing">12</property>
+                                    <property name="visible">True</property>
+                                    <property name="can_focus">False</property>
+                                    <property name="spacing">12</property>
                                     <child>
                                       <object class="GtkGrid" id="time_grid">
                                         <property name="visible">True</property>
                                         <property name="can_focus">False</property>
                                         <property name="hexpand">True</property>
-                                        <property name="column-homogeneous">True</property>
                                         <property name="column_spacing">6</property>
                                         <child>
                                           <object class="GtkLabel" id="activate_delay_label">
                                             <property name="visible">True</property>
                                             <property name="can_focus">False</property>
+                                            <property name="halign">start</property>
+                                            <property name="hexpand">False</property>
                                             <property name="label" translatable="yes">Regard the computer as _idle after:</property>
                                             <property name="use_underline">True</property>
                                           </object>
@@ -422,13 +423,14 @@
                                           <object class="GtkScale" id="activate_delay_hscale">
                                             <property name="visible">True</property>
                                             <property name="can_focus">True</property>
+                                            <property name="hexpand">True</property>
                                             <property name="adjustment">adjustment1</property>
                                             <property name="digits">0</property>
                                           </object>
                                           <packing>
                                             <property name="left_attach">1</property>
                                             <property name="top_attach">0</property>
-                                            <property name="width">3</property>
+                                            <property name="width">1</property>
                                             <property name="height">1</property>
                                           </packing>
                                         </child>
@@ -436,6 +438,8 @@
                                           <object class="GtkLabel" id="lock_delay_label">
                                             <property name="visible">True</property>
                                             <property name="can_focus">False</property>
+                                            <property name="halign">start</property>
+                                            <property name="hexpand">False</property>
                                             <property name="label" translatable="yes">Time before locking:</property>
                                             <property name="use_underline">True</property>
                                           </object>
@@ -450,13 +454,14 @@
                                           <object class="GtkScale" id="lock_delay_hscale">
                                             <property name="visible">True</property>
                                             <property name="can_focus">True</property>
+                                            <property name="hexpand">True</property>
                                             <property name="adjustment">adjustment2</property>
                                             <property name="digits">0</property>
                                           </object>
                                           <packing>
                                             <property name="left_attach">1</property>
                                             <property name="top_attach">1</property>
-                                            <property name="width">3</property>
+                                            <property name="width">1</property>
                                             <property name="height">1</property>
                                           </packing>
                                         </child>
```

2024-05-14 17:40 UTC, cwendling commented on src/mate-screensaver-preferences.c
> +		return g_strdup_printf (_("Never                      "));
This is entirely silly, but I now understand why you did that: apparently, GTK computes the width of the label by testing the first and last values on the range and using the largest one. As the max is "2 hours", the min is "Never", it wrapps longer values such as "1 hour 15 minutes".

I'll see whether I can find a better fix for this, because this doesn't sound like one.

2024-05-14 17:40 UTC, cwendling commented on src/mate-screensaver-preferences.c
> +		return g_strdup_printf (_("Never                      "));
"Never" sounds wrong: it's actually not used for the activate delay, and for the lock delay "0" means "immediately after activation", not "never lock" (that is the checkbox "Lock screen when screensaver is active")

2024-05-14 17:40 UTC, cwendling commented on src/mate-screensaver-preferences.c
> +		return g_strdup_printf (_("Never                      "));
BTW, at least use something like `g_strdup_printf ("%-27s", _("Never"));`: it's both clearer and doesn't make a silly translatable string.

2024-05-15 01:30 UTC, zhuyaliang commented on src/mate-screensaver-preferences.c
> +		return g_strdup_printf (_("Never                      "));
This is indeed a foolish code. Thank you for reminding me to use ```g_strdup_printf ("% -27s", _ ("Never"))```

2024-05-15 20:23 UTC, cwendling commented
@zhuyaliang I ended up making quite a few changes, see https://github.com/mate-desktop/mate-screensaver/compare/lock-delay...cwendling:mate-screensaver:lock-delay
What do you think of those?

2024-05-16 02:38 UTC, zhuyaliang commented
@cwendling It looks great. Please merge this PR and initiate a new one. I will review the code as soon as possible

2024-05-16 08:10 UTC, cwendling commented
> Please merge this PR and initiate a new one.

merge this one first, or replace it with one containing the fixes?

2024-05-16 08:21 UTC, zhuyaliang commented
My suggestion is to merge this first, and then review and merge your repair PR

2024-05-16 08:28 UTC, merged

2024-05-16 08:35 UTC, zhuyaliang commented
@cwendling 
> I ended up making quite a few changes, see https://github.com/mate-desktop/mate-screensaver/compare/lock-delay...cwendling:mate-screensaver:lock-delay
What do you think of those?

This is your labor success, I need your consent